version: "3.7"
volumes:
  rabbitmq-data:
  postgres-data:
services:
   pact-broker-db:
      image: postgres
      volumes:
        - postgres-data:/var/lib/postgresql
      healthcheck:
        test: psql postgres --command "select 1" -U postgres
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: IzolrcOJaGl9OYZj49CM
        POSTGRES_DB: postgres

   pact-broker_app:
      image: dius/pact-broker
      links:
        - pact-broker-db
      ports:
        - "9091:80"
      environment:
        PACT_BROKER_DATABASE_USERNAME: postgres
        PACT_BROKER_DATABASE_PASSWORD: IzolrcOJaGl9OYZj49CM
        PACT_BROKER_DATABASE_HOST: postgres
        PACT_BROKER_DATABASE_NAME: postgres

   rabbitmq:
      image: rabbitmq:3.7-management
      volumes:
          - rabbitmq-data:/var/lib/rabbitmq
      ports:
         - "15672:15672"
         - "5672:5672"